### ISSUE TITLE
Wlan not working from time to time

### ISSUE THREAD

**Issue by romses** [MatthewBooth/JFLTE-GPE#8]
Hi

I am using this rom on my jflte.

From time to time, i becone disconnected from my wlan with some authentication errors.
Manually reconnecting solves the problem imediatly.
This error often occurs, when i am entering a known wlan, and when i am useng dropbox-sync in titanium backup.

**Comment by MusicManiak** [comment]
Do u have the latest modem/bootloader?

**Comment by 0o0TheDude0o0** [comment]
That is really strange, I have never had a single issue with wifi. What phone model, network, and modem are you on exactly? Clean flash, dirty flash? Most important, is this every access point you are connecting (have connected) to or just a specific wifi network you are having trouble with? Have you restored to stock with factory MDK odin images and started over from scratch? What AP are you running and have you flashed a custom firmware to it (eg DD-WRT) and are you within an acceptable distance from it or on the edge of the wifi network? Also, is it WEP, WPA..  Are you connecting with AOSS/WPS "one touch"?

**Comment by romses** [comment]
I've made a clean install with a full whipe.

My baseband-version is I9505XXUFNB9

Under CM11 i did not have any issues with my wlan.

**Comment by romses** [comment]
Today, i updated my baseband to I9505XXUFNDG.
I still have the wlan issues

**Comment by 0o0TheDude0o0** [comment]
All I can suggest is going ALL the way back to stock. There is probably a different odin one click for your device but as an example I would use this http://forum.xda-developers.com/showthread.php?t=2289325 and http://forum.xda-developers.com/showthread.php?t=2290798 . This takes my device back to the factory MDK state. Then I proceed with rooting etc and then install the new rom. It is a super pain in the ass but when you are having unexplained problems that no one else is experiencing this is the only way to isolate the problem and troubleshoot. Cyanogenmod has been known to cause some strange issues that are only resolved with this method.

**Comment by romses** [comment]
Hi

I now returned to stock, and back.
I updated my Bootloader and my Baseband to I9505XXUNGK4.
I still have these WLAN issues. Any Ideas?

**Comment by ounos** [comment]
Samsung Galaxy S4 I9505 here.

I have the same issue. I can't connect to wlan. Any ideas ?

**Comment by airwavesIRE** [comment]
Same issue here.  If I put the phone in hot-spot / tether mode and then take it out then usually Wifi will not connect properly. 

A reboot will fix it. 

I'm using latest version of rom on an I9505

**Comment by romses** [comment]
Hello

I Identified Titanium Backup as the wlan killer.
Every time, TB is backing up my wlan settings, it has to interrupt my wlan connection. After that, i cannot reconnect. I now excluded wlan backups in TB.

**Comment by Bartik168** [comment]
@romses : Same here, I also excluded wi-fi from TB backup:-(

**Comment by airwavesIRE** [comment]
I'm not using TV Backup.  I've done a full factory  wipe,  formatted system and data and flashed again and so far no issues. 
I only done a factory reset last time and it seemed to cause issues. 
Using the Dark setting's and dialer also seemed to make the rom very laggy
